#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 25 00:40:42 JST 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim test_array_behav -key {Behavioral:sim_1:Functional:test_array} -tclbatch test_array.tcl -view /home/y/project/array3/test_array_behav.wcfg -log simulate.log"
xsim test_array_behav -key {Behavioral:sim_1:Functional:test_array} -tclbatch test_array.tcl -view /home/y/project/array3/test_array_behav.wcfg -log simulate.log

